services:
  - type: web
    name: urlshortener
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn urlshortener.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: 4